issue:
  invalid:
    mark: ng-zorro-issue-helper
    labels: Invalid
    replay: |
      Hello @{user}, your issue has been closed because it does not conform to our issue requirements.
      Please use the [Issue Helper](http://ng.ant.design/issue-helper/#/en) to create an issue, thank you!


      你好 @{user}，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。
      你可以通过 [issue 助手](http://ng.ant.design/issue-helper/#/zh) 来创建 issue 以方便我们定位错误。谢谢配合！
  assignOwner:
    Affix: cipchk
    Alert: vthinkxie
    Anchor: cipchk
    AutoComplete: hsuanxyz
    Avatar: hsuanxyz
    BackTop: cipchk
    Badge: hsuanxyz
    Breadcrumb: wendzhue
    Button: vthinkxie
    Empty: wendzhue
    Calendar: wenqi73
    Card: vthinkxie
    Carousel: wendzhue
    Cascader: wendzhue
    Comment: hsuanxyz
    Checkbox: vthinkxie
    Collapse: vthinkxie
    DatePicker: wenqi73
    Divider: vthinkxie
    Descriptions: wendzhue
    Drawer: hsuanxyz
    Dropdown: vthinkxie
    Form: vthinkxie
    Grid: vthinkxie
    Icon: wendzhue
    Input: vthinkxie
    InputNumber: vthinkxie
    Layout: vthinkxie
    List: cipchk
    Mention: hsuanxyz
    Menu: vthinkxie
    Message: wendzhue
    Modal: hsuanxyz
    Notification: wendzhue
    PageHeader: hsuanxyz
    Pagination: vthinkxie
    Popconfirm: wendzhue
    Popover: wendzhue
    Progress: wendzhue
    Radio: vthinkxie
    Rate: wendzhue
    Select: vthinkxie
    Slider: wendzhue
    Spin: vthinkxie
    Statistic: wendzhue
    Steps: hsuanxyz
    Skeleton: wenqi73
    Switch: vthinkxie
    Table: vthinkxie
    Tabs: vthinkxie
    Tag: hsuanxyz
    TimePicker: wenqi73
    Timeline: wendzhue
    Tooltip: wendzhue
    Transfer: cipchk
    Tree: simplejason
    TreeSelect: hsuanxyz
    Typography: hsuanxyz
    Upload: cipchk
